### ISSUE TITLE
Icon disappears in Firefox dark theme

### ISSUE THREAD

**Issue by rhardih** [rhardih/ekill#11]
Example:

<img width="183" alt="screen shot 2018-10-07 at 20 42 02" src="https://user-images.githubusercontent.com/124250/46585522-350e1d00-ca72-11e8-93bb-b35a982aa50f.png">

See https://stackoverflow.com/questions/48540523/firefox-pick-page-action-icon-for-dark-light-themes for a possible solution.

CC @Yoric

**Comment by tiansh** [comment]
The SO question linked is talking about page_action instead of browser_action which is not related. You should follow theme_icons described in [browser_action MDN artical](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/manifest.json/browser_action).

**Comment by rhardih** [comment]
@tiansh Seems to only be FF using *theme_icons* under "browser_action", but I guess that'll do for now.

https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/manifest.json/browser_action vs. https://developer.chrome.com/extensions/browserAction

**Comment by rhardih** [comment]
Tried to match the native color as best I could:

<img width="226" alt="screen shot 2018-10-08 at 23 27 38" src="https://user-images.githubusercontent.com/124250/46635155-abcf1700-cb53-11e8-84e5-4fdb5bad8755.png">
