### ISSUE TITLE
Add a badge to icon, with number of killed elements for Grudge

### ISSUE THREAD

**Issue by rhardih** [rhardih/ekill#19]
<img width="57" alt="screen shot 2018-10-18 at 12 27 27" src="https://user-images.githubusercontent.com/124250/47148550-486e8300-d2d1-11e8-8d7a-c9d2267a330a.png">

**Comment by duart38** [comment]
all elements in grudge or for a specific host?

**Comment by rhardih** [comment]
I'm think it should be an indicator of "How many elements was killed on the currrent page?". Kind of like how it is for various ad-blockers. For instance, uBlock looks like this:

<img width="53" alt="screen shot 2018-10-18 at 22 43 01" src="https://user-images.githubusercontent.com/124250/47182985-34557080-d327-11e8-9940-bece770b98ec.png">

**Comment by duart38** [comment]
ah yes, i made something like this in my fork, currently it shows all grudge elements, will change to active page
