### ISSUE TITLE
Deactivate "kill" mode

### ISSUE THREAD

**Issue by j3r3miah** [rhardih/ekill#2]
If I activate ekill but then decide there isn't anything I want to kill, there's no way to get out of "kill" mode (skull+crossbones cursor). Activating the extension again (like via hotkey) should ideally toggle in and out of kill mode.

Love this thing, thanks!

**Comment by rhardih** [comment]
Yeah, I thought about just using Esc, but I like the toggle idea as well. I'll look into it.

**Comment by j3r3miah** [comment]
Either way works. Thanks!
