### ISSUE TITLE
Port to Firefox WebExtension?

### ISSUE THREAD

**Issue by Yoric** [rhardih/ekill#4]
I would definitely install this on my Firefox :)

**Comment by rhardih** [comment]
Not a bad idea. I'll keep this issue open, in case I have some time to look into a port at some point. 👍

**Comment by SphinxKnight** [comment]
as far as I can tell, apart from the hotkey configuration (and the icon of the addon), I was able to package/run the extension in Firefox without any change at all :) (using web-ext /build/sign)

**Comment by rhardih** [comment]
Took a few minor modifications but seems to work fine.

Available at:

https://addons.mozilla.org/firefox/addon/ekill/

**Comment by Yoric** [comment]
Seems to work \o/

One nitpick: the icon is hardly visible when I'm using black theme.

**Comment by rhardih** [comment]
Ah, I see what you mean.

<img width="183" alt="screen shot 2018-10-07 at 20 42 02" src="https://user-images.githubusercontent.com/124250/46585474-88cc3680-ca71-11e8-8079-bf79bb9a1b75.png">

Seems the solution is to switch to an svg based icon and using fill-opacity in that case. I'll open a new issue.

**Comment by dmose** [comment]
This is great; thanks so much!
