### ISSUE TITLE
Too much permission?

### ISSUE THREAD

**Issue by glaforge** [rhardih/ekill#5]
https://github.com/rhardih/ekill/blob/ba7b644f94b9b859b76a8dfb736ced98f848f7f2/manifest.json#L7

You request access to tabs and all URLs, that could potentially be forwarded / leaked somewhere at some point. What about just accessing the activeTab permission instead?

https://developer.chrome.com/extensions/activeTab

The less permissions needed by an extension, the better :-)

**Comment by rhardih** [comment]
Sounds like a good idea! Will fix.
